### ISSUE TITLE
To-do List 7/27

### ISSUE THREAD

**Issue by kqlapwo** [kqlapwo/kqlapwo.io#1]
- [ ] 스탯창 만들기 (슈팅, 유효슈팅, 패스, 점유율 등.......)
- [ ] 축구 메인 기능 추가 하기 (일정, 달력, 팀 등......)
- [ ] 팀별 스탯 기능 추가하기 (팀내 선수별 스탯)
- [ ] 순위창 추가하기
